name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open a TypeScript file with...
        2. Type '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: If applicable, provide a minimal code sample that reproduces the issue.
      render: typescript
      placeholder: |
        // Minimal reproduction code
        const example = ...

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: editor
    attributes:
      label: Editor / IDE
      description: What editor are you using?
      placeholder: "VSCode 1.85.0"
    validations:
      required: true

  - type: input
    id: server-version
    attributes:
      label: Language Server Version
      description: Version of typescript-language-server-rust
      placeholder: "0.1.0"

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: If applicable, paste any relevant log output.
      render: shell
      placeholder: |
        Paste log output here...
        (View > Output > TypeScript/JavaScript LSP (Rust))

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I have included all relevant information above
          required: true

